platform:
    - x64

cache:
    - C:\Users\appveyor\.esy\3_\i
    - C:\Users\appveyor\.esy\source-tarballs

install:
    # The x64 is required as a workaround for esy/esy#412
    - ps: Install-Product node 8 x64
    - npm install -g esy@0.3.0

build_script:
    - node test.js

test: off
